import './globals.css'
import { Providers } from '@/redux/provider'
export const metadata = {
  title: 'Botnostic Credential Manager',
  description: 'Generated by Botnostic credential Manager',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#EFEFEF] font-poppins" >
        <Providers>
        {children}
        </Providers>
        </body>
    </html>
  )
}
